#include "ros_weaver/core/nav2_exporter.hpp"
#include <QFile>
#include <QTextStream>
#include <QDateTime>
#include <cmath>

namespace ros_weaver {

QString Nav2Exporter::exportMission(const Mission& mission, Format format) {
  switch (format) {
    case Nav2WaypointFollower:
      return generateWaypointFollowerYAML(mission);
    case Nav2BtNavigator:
      return generateNavigationBT(mission);
    case PoseArray:
      return generatePoseArrayYAML(mission);
    case CustomYAML:
      return generateCustomYAML(mission);
    case PythonScript:
      return generatePythonScript(mission);
    case LaunchFile:
      return generateLaunchFile(mission);
    default:
      return QString();
  }
}

bool Nav2Exporter::saveToFile(const Mission& mission, Format format, const QString& filePath) {
  QString content = exportMission(mission, format);
  if (content.isEmpty()) {
    return false;
  }

  QFile file(filePath);
  if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
    return false;
  }

  QTextStream out(&file);
  out << content;
  return true;
}

QString Nav2Exporter::generateWaypointFollowerYAML(const Mission& mission) {
  QString output;
  QTextStream stream(&output);

  stream << "# Nav2 Waypoint Follower Configuration\n";
  stream << "# Generated by ROS2Weaver Mission Planner\n";
  stream << "# Mission: " << mission.name << "\n";
  stream << "# Generated: " << QDateTime::currentDateTime().toString(Qt::ISODate) << "\n\n";

  stream << "waypoint_follower:\n";
  stream << "  ros__parameters:\n";
  stream << "    loop_rate: 20\n";
  stream << "    stop_on_failure: false\n";
  stream << "    waypoint_task_executor_plugin: \"wait_at_waypoint\"\n\n";

  stream << "    waypoints:\n";
  for (int i = 0; i < mission.waypoints.size(); ++i) {
    const Waypoint& wp = mission.waypoints[i];
    stream << "      - name: \"" << wp.name << "\"\n";
    stream << waypointToPoseYAML(wp, 8);

    // Add tolerance
    stream << "        tolerance: " << QString::number(wp.tolerance, 'f', 3) << "\n";

    // Add behavior triggers as task executor parameters
    if (!wp.triggers.isEmpty()) {
      stream << "        tasks:\n";
      for (const auto& trigger : wp.triggers) {
        stream << "          - type: \"" << BehaviorTrigger::triggerTypeToString(trigger.type) << "\"\n";
        if (trigger.type == BehaviorTrigger::OnApproach) {
          stream << "            approach_distance: "
                 << QString::number(trigger.approachDistance, 'f', 2) << "\n";
        }
        if (!trigger.behaviorTreeId.isEmpty()) {
          stream << "            behavior_tree: \"" << trigger.behaviorTreeId << "\"\n";
        }
      }
    }
    stream << "\n";
  }

  // Mission settings
  stream << "    # Mission settings\n";
  stream << "    loop_mission: " << (mission.loopMission ? "true" : "false") << "\n";
  if (mission.loopMission && mission.loopCount > 0) {
    stream << "    loop_count: " << mission.loopCount << "\n";
  }
  stream << "    default_speed: " << QString::number(mission.defaultSpeed, 'f', 2) << "\n\n";

  // Initial pose
  stream << "    initial_pose:\n";
  stream << "      position:\n";
  stream << "        x: " << QString::number(mission.startPose.x, 'f', 3) << "\n";
  stream << "        y: " << QString::number(mission.startPose.y, 'f', 3) << "\n";
  stream << "        z: 0.0\n";
  stream << "      orientation:\n";
  stream << quaternionFromYaw(mission.startPose.theta);

  return output;
}

QString Nav2Exporter::generateNavigationBT(const Mission& mission) {
  QString output;
  QTextStream stream(&output);

  stream << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
  stream << "<!-- Navigation Behavior Tree -->\n";
  stream << "<!-- Mission: " << mission.name << " -->\n";
  stream << "<!-- Generated by ROS2Weaver Mission Planner -->\n\n";

  stream << "<root BTCPP_format=\"4\" main_tree_to_execute=\"MissionTree\">\n\n";

  stream << "  <BehaviorTree ID=\"MissionTree\">\n";

  if (mission.loopMission) {
    stream << "    <Repeat num_cycles=\"" << (mission.loopCount > 0 ? mission.loopCount : -1) << "\">\n";
    stream << "      <Sequence>\n";
  } else {
    stream << "    <Sequence>\n";
  }

  QString indent1 = mission.loopMission ? "        " : "      ";

  // Generate navigate to each waypoint
  for (int i = 0; i < mission.waypoints.size(); ++i) {
    const Waypoint& wp = mission.waypoints[i];

    stream << indent1 << "<!-- Waypoint " << (i + 1) << ": " << wp.name << " -->\n";

    // Add approach triggers
    for (const auto& trigger : wp.triggers) {
      if (trigger.type == BehaviorTrigger::OnApproach) {
        stream << generateBehaviorTriggerBT(trigger, wp.name);
      }
    }

    // Navigate to waypoint
    stream << indent1 << "<NavigateToPose goal=\"{goal_" << wp.id << "}\" />\n";

    // Add arrival triggers
    for (const auto& trigger : wp.triggers) {
      if (trigger.type == BehaviorTrigger::OnArrival) {
        stream << generateBehaviorTriggerBT(trigger, wp.name);
      }
    }

    stream << "\n";
  }

  if (mission.loopMission) {
    stream << "      </Sequence>\n";
    stream << "    </Repeat>\n";
  } else {
    stream << "    </Sequence>\n";
  }

  stream << "  </BehaviorTree>\n\n";

  // Add blackboard values for waypoints
  stream << "  <!-- Waypoint goal poses -->\n";
  stream << "  <TreeNodesModel>\n";
  for (const auto& wp : mission.waypoints) {
    stream << "    <SetBlackboard output_key=\"goal_" << wp.id << "\" value=\"";
    stream << wp.x << ";" << wp.y << ";" << wp.theta << "\" />\n";
  }
  stream << "  </TreeNodesModel>\n\n";

  stream << "</root>\n";

  return output;
}

QString Nav2Exporter::generatePoseArrayYAML(const Mission& mission) {
  QString output;
  QTextStream stream(&output);

  stream << "# Pose Array for Navigation\n";
  stream << "# Mission: " << mission.name << "\n\n";

  stream << "header:\n";
  stream << "  frame_id: \"" << mission.startPose.frameId << "\"\n\n";

  stream << "poses:\n";
  for (const auto& wp : mission.waypoints) {
    stream << "  - position:\n";
    stream << "      x: " << QString::number(wp.x, 'f', 4) << "\n";
    stream << "      y: " << QString::number(wp.y, 'f', 4) << "\n";
    stream << "      z: 0.0\n";
    stream << "    orientation:\n";
    stream << quaternionFromYaw(wp.theta);
  }

  return output;
}

QString Nav2Exporter::generateCustomYAML(const Mission& mission) {
  QString output;
  QTextStream stream(&output);

  stream << "# ROS2Weaver Mission Definition\n";
  stream << "# Version: 1.0\n\n";

  stream << "mission:\n";
  stream << "  name: \"" << mission.name << "\"\n";
  stream << "  description: \"" << mission.description << "\"\n";
  stream << "  loop: " << (mission.loopMission ? "true" : "false") << "\n";
  stream << "  loop_count: " << mission.loopCount << "\n";
  stream << "  default_speed: " << QString::number(mission.defaultSpeed, 'f', 2) << "\n";
  stream << "  default_tolerance: " << QString::number(mission.defaultTolerance, 'f', 2) << "\n\n";

  stream << "  start_pose:\n";
  stream << "    frame_id: \"" << mission.startPose.frameId << "\"\n";
  stream << "    x: " << QString::number(mission.startPose.x, 'f', 4) << "\n";
  stream << "    y: " << QString::number(mission.startPose.y, 'f', 4) << "\n";
  stream << "    theta: " << QString::number(mission.startPose.theta, 'f', 4) << "\n\n";

  stream << "  waypoints:\n";
  for (const auto& wp : mission.waypoints) {
    stream << "    - id: " << wp.id << "\n";
    stream << "      name: \"" << wp.name << "\"\n";
    stream << "      x: " << QString::number(wp.x, 'f', 4) << "\n";
    stream << "      y: " << QString::number(wp.y, 'f', 4) << "\n";
    stream << "      theta: " << QString::number(wp.theta, 'f', 4) << "\n";
    stream << "      tolerance: " << QString::number(wp.tolerance, 'f', 3) << "\n";

    if (!wp.triggers.isEmpty()) {
      stream << "      triggers:\n";
      for (const auto& trigger : wp.triggers) {
        stream << "        - type: " << BehaviorTrigger::triggerTypeToString(trigger.type) << "\n";
        if (trigger.type == BehaviorTrigger::OnApproach) {
          stream << "          approach_distance: " << QString::number(trigger.approachDistance, 'f', 2) << "\n";
        }
        stream << "          behavior_tree: \"" << trigger.behaviorTreeId << "\"\n";
      }
    }
    stream << "\n";
  }

  return output;
}

QString Nav2Exporter::generatePythonScript(const Mission& mission) {
  QString output;
  QTextStream stream(&output);

  stream << "#!/usr/bin/env python3\n";
  stream << "\"\"\"Nav2 Mission Script - " << mission.name << "\"\"\"\n";
  stream << "# Generated by ROS2Weaver Mission Planner\n\n";

  stream << "import rclpy\n";
  stream << "from rclpy.node import Node\n";
  stream << "from geometry_msgs.msg import PoseStamped\n";
  stream << "from nav2_simple_commander.robot_navigator import BasicNavigator\n";
  stream << "import math\n\n";

  stream << "def create_pose(x: float, y: float, theta: float, frame_id: str = 'map') -> PoseStamped:\n";
  stream << "    \"\"\"Create a PoseStamped message from x, y, theta.\"\"\"\n";
  stream << "    pose = PoseStamped()\n";
  stream << "    pose.header.frame_id = frame_id\n";
  stream << "    pose.pose.position.x = x\n";
  stream << "    pose.pose.position.y = y\n";
  stream << "    pose.pose.orientation.z = math.sin(theta / 2.0)\n";
  stream << "    pose.pose.orientation.w = math.cos(theta / 2.0)\n";
  stream << "    return pose\n\n";

  stream << "def main():\n";
  stream << "    rclpy.init()\n";
  stream << "    navigator = BasicNavigator()\n\n";

  stream << "    # Set initial pose\n";
  stream << "    initial_pose = create_pose(\n";
  stream << "        " << QString::number(mission.startPose.x, 'f', 4) << ",\n";
  stream << "        " << QString::number(mission.startPose.y, 'f', 4) << ",\n";
  stream << "        " << QString::number(mission.startPose.theta, 'f', 4) << "\n";
  stream << "    )\n";
  stream << "    navigator.setInitialPose(initial_pose)\n";
  stream << "    navigator.waitUntilNav2Active()\n\n";

  stream << "    # Define waypoints\n";
  stream << "    waypoints = [\n";
  for (const auto& wp : mission.waypoints) {
    stream << "        create_pose("
           << QString::number(wp.x, 'f', 4) << ", "
           << QString::number(wp.y, 'f', 4) << ", "
           << QString::number(wp.theta, 'f', 4) << "),  # " << wp.name << "\n";
  }
  stream << "    ]\n\n";

  if (mission.loopMission) {
    stream << "    # Execute mission with looping\n";
    if (mission.loopCount > 0) {
      stream << "    for i in range(" << mission.loopCount << "):\n";
    } else {
      stream << "    while rclpy.ok():\n";
    }
    stream << "        navigator.followWaypoints(waypoints)\n";
    stream << "        while not navigator.isTaskComplete():\n";
    stream << "            feedback = navigator.getFeedback()\n";
    stream << "            # Add any feedback processing here\n";
    stream << "            pass\n\n";
  } else {
    stream << "    # Execute mission\n";
    stream << "    navigator.followWaypoints(waypoints)\n";
    stream << "    while not navigator.isTaskComplete():\n";
    stream << "        feedback = navigator.getFeedback()\n";
    stream << "        pass\n\n";
  }

  stream << "    result = navigator.getResult()\n";
  stream << "    print(f'Mission completed with result: {result}')\n\n";
  stream << "    rclpy.shutdown()\n\n";

  stream << "if __name__ == '__main__':\n";
  stream << "    main()\n";

  return output;
}

QString Nav2Exporter::generateLaunchFile(const Mission& mission) {
  QString output;
  QTextStream stream(&output);

  stream << "# ROS2 Launch file for mission: " << mission.name << "\n";
  stream << "# Generated by ROS2Weaver Mission Planner\n\n";

  stream << "from launch import LaunchDescription\n";
  stream << "from launch_ros.actions import Node\n";
  stream << "from launch.actions import DeclareLaunchArgument\n";
  stream << "from launch.substitutions import LaunchConfiguration\n";
  stream << "import os\n";
  stream << "from ament_index_python.packages import get_package_share_directory\n\n";

  stream << "def generate_launch_description():\n";
  stream << "    return LaunchDescription([\n";
  stream << "        # Add Nav2 nodes or include Nav2 launch file here\n";
  stream << "        # Node(\n";
  stream << "        #     package='nav2_waypoint_follower',\n";
  stream << "        #     executable='waypoint_follower',\n";
  stream << "        #     name='waypoint_follower',\n";
  stream << "        #     parameters=['path/to/waypoint_config.yaml'],\n";
  stream << "        # ),\n";
  stream << "    ])\n";

  return output;
}

QString Nav2Exporter::getDefaultExtension(Format format) {
  switch (format) {
    case Nav2WaypointFollower:
    case PoseArray:
    case CustomYAML:
      return ".yaml";
    case Nav2BtNavigator:
      return ".xml";
    case PythonScript:
      return ".py";
    case LaunchFile:
      return "_launch.py";
    default:
      return ".txt";
  }
}

QString Nav2Exporter::getFormatDescription(Format format) {
  switch (format) {
    case Nav2WaypointFollower:
      return "Nav2 Waypoint Follower YAML";
    case Nav2BtNavigator:
      return "Behavior Tree XML";
    case PoseArray:
      return "Pose Array YAML";
    case CustomYAML:
      return "Custom Mission YAML";
    case PythonScript:
      return "Python Navigation Script";
    case LaunchFile:
      return "ROS2 Launch File";
    default:
      return "Unknown";
  }
}

QString Nav2Exporter::waypointToPoseYAML(const Waypoint& wp, int indentLevel) {
  QString output;
  QTextStream stream(&output);
  QString ind = indent(indentLevel);

  stream << ind << "pose:\n";
  stream << ind << "  position:\n";
  stream << ind << "    x: " << QString::number(wp.x, 'f', 4) << "\n";
  stream << ind << "    y: " << QString::number(wp.y, 'f', 4) << "\n";
  stream << ind << "    z: 0.0\n";
  stream << ind << "  orientation:\n";
  stream << quaternionFromYaw(wp.theta).replace("\n", "\n" + ind + "  ");

  return output;
}

QString Nav2Exporter::generateBehaviorTriggerBT(const BehaviorTrigger& trigger,
                                                  const QString& waypointName) {
  QString output;
  QTextStream stream(&output);

  QString triggerStr = BehaviorTrigger::triggerTypeToString(trigger.type);
  stream << "        <!-- " << triggerStr << " trigger for " << waypointName << " -->\n";

  if (!trigger.behaviorTreeId.isEmpty()) {
    stream << "        <SubTree ID=\"" << trigger.behaviorTreeId << "\" />\n";
  }

  return output;
}

QString Nav2Exporter::quaternionFromYaw(double theta) {
  QString output;
  QTextStream stream(&output);

  double qz = std::sin(theta / 2.0);
  double qw = std::cos(theta / 2.0);

  stream << "        x: 0.0\n";
  stream << "        y: 0.0\n";
  stream << "        z: " << QString::number(qz, 'f', 6) << "\n";
  stream << "        w: " << QString::number(qw, 'f', 6) << "\n";

  return output;
}

QString Nav2Exporter::indent(int level) {
  return QString(level, ' ');
}

}  // namespace ros_weaver
