#ifndef ROS_WEAVER_CORE_DATA_LINEAGE_HPP
#define ROS_WEAVER_CORE_DATA_LINEAGE_HPP

#include <QString>
#include <QStringList>
#include <QJsonObject>
#include <QList>
#include <QVariant>

namespace ros_weaver {

// Type of data source
enum class LineageSourceType {
  Unknown,           // Source cannot be determined
  ProjectFile,       // From .rwp project file
  YamlFile,          // From YAML configuration file
  SourceCodeFile,    // From C++/Python source file
  RosTopic,          // From live ROS2 topic data
  RosParameter,      // From ROS2 parameter server
  Generated,         // Generated by ROS Weaver (code generation)
  UserInput,         // Direct user input in UI
  SystemDiscovery    // Discovered from running ROS2 system
};

// Represents a single point in the data lineage chain
struct LineageNode {
  LineageSourceType sourceType;
  QString sourcePath;        // File path or topic name
  int lineNumber;            // Line number in file (0 if not applicable)
  int columnNumber;          // Column number (0 if not applicable)
  QString description;       // Human-readable description of this source
  QString dataKey;           // Key/field name within the source (e.g., param name)
  QVariant dataValue;        // The actual value at this point (optional)
  QString timestamp;         // When this data was captured (for live data)

  // Check if this source is editable in an editor
  bool isEditable() const;

  // Get a display-friendly source type name
  QString sourceTypeName() const;

  // Serialization
  QJsonObject toJson() const;
  static LineageNode fromJson(const QJsonObject& json);
};

// Complete lineage chain for a piece of data
class DataLineage {
public:
  DataLineage();
  explicit DataLineage(const LineageNode& primarySource);

  // Primary source (most direct origin)
  void setPrimarySource(const LineageNode& source);
  const LineageNode& primarySource() const { return primarySource_; }

  // Additional sources in the chain (indirect origins)
  void addIntermediateSource(const LineageNode& source);
  const QList<LineageNode>& intermediateChain() const { return intermediateChain_; }

  // Description of the data being traced
  void setDataDescription(const QString& desc) { dataDescription_ = desc; }
  QString dataDescription() const { return dataDescription_; }

  // Check if lineage is valid/known
  bool isKnown() const;

  // Check if any source in the chain is editable
  bool hasEditableSource() const;

  // Get the first editable source in the chain
  LineageNode firstEditableSource() const;

  // Get complete lineage as a formatted string
  QString toDisplayString() const;

  // Serialization
  QJsonObject toJson() const;
  static DataLineage fromJson(const QJsonObject& json);

  // Factory methods for common lineage types
  static DataLineage fromProjectFile(const QString& projectPath,
                                      const QString& dataKey,
                                      int lineNumber = 0);
  static DataLineage fromYamlFile(const QString& yamlPath,
                                   const QString& paramName,
                                   int lineNumber = 0);
  static DataLineage fromSourceFile(const QString& filePath,
                                     int lineNumber,
                                     const QString& description);
  static DataLineage fromRosTopic(const QString& topicName,
                                   const QString& messageType);
  static DataLineage fromGenerated(const QString& generatedPath,
                                    const QString& templateSource);
  static DataLineage fromUserInput(const QString& widgetName,
                                    const QString& fieldName);

private:
  LineageNode primarySource_;
  QList<LineageNode> intermediateChain_;
  QString dataDescription_;
};

// Utility class for opening files in VS Code
class VsCodeIntegration {
public:
  // Open a file in VS Code at a specific line
  static bool openFile(const QString& filePath, int lineNumber = 0, int column = 0);

  // Check if VS Code is available
  static bool isAvailable();

  // Get the VS Code command (code, code-insiders, etc.)
  static QString vsCodeCommand();
};

// Interface for widgets that support lineage tracking
class LineageAware {
public:
  virtual ~LineageAware() = default;

  // Get lineage for the currently selected/focused item
  virtual DataLineage currentItemLineage() const = 0;

  // Check if the widget has lineage information available
  virtual bool hasLineageInfo() const = 0;
};

}  // namespace ros_weaver

#endif  // ROS_WEAVER_CORE_DATA_LINEAGE_HPP
